// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model

import "github.com/gogf/gf/os/gtime"



// Permission is the golang structure for table permission.
type Permission struct {
    Id       int         `orm:"id,primary" json:"id"`       //           
    Name     string      `orm:"name"       json:"name"`     // 权限名称  
    Uri      string      `orm:"uri"        json:"uri"`      // 权限地址  
    CreateAt *gtime.Time `orm:"create_at"  json:"createAt"` // 添加时间  
    UpdateAt *gtime.Time `orm:"update_at"  json:"updateAt"` // 编辑时间  
    DeleteAt *gtime.Time `orm:"delete_at"  json:"deleteAt"` // 删除时间  
}


// Role is the golang structure for table role.
type Role struct {
    Id       int         `orm:"id,primary" json:"id"`       //         
    Name     string      `orm:"name"       json:"name"`     // 角色名  
    CreateAt *gtime.Time `orm:"create_at"  json:"createAt"` //         
    UpdateAt *gtime.Time `orm:"update_at"  json:"updateAt"` //         
    DeleteAt *gtime.Time `orm:"delete_at"  json:"deleteAt"` //         
}


// RolePermission is the golang structure for table role_permission.
type RolePermission struct {
    Id           int `orm:"id,primary"    json:"id"`           //         
    RoleId       int `orm:"role_id"       json:"roleId"`       // 角色id  
    PermissionId int `orm:"permission_id" json:"permissionId"` // 权限id  
}


// User is the golang structure for table user.
type User struct {
    Id       int         `orm:"id,primary" json:"id"`       //                     
    Username string      `orm:"username"   json:"username"` // 用户名              
    Password string      `orm:"password"   json:"password"` // 密码                
    Salt     string      `orm:"salt"       json:"salt"`     // 盐值                
    Status   int         `orm:"status"     json:"status"`   // 状态，0封禁，1正常  
    CreateAt *gtime.Time `orm:"create_at"  json:"createAt"` // 添加时间            
    UpdateAt *gtime.Time `orm:"update_at"  json:"updateAt"` // 更新时间            
    DeleteAt *gtime.Time `orm:"delete_at"  json:"deleteAt"` // 删除时间            
}


// UserPermission is the golang structure for table user_permission.
type UserPermission struct {
    Id           int `orm:"id,primary"    json:"id"`           //         
    UserId       int `orm:"user_id"       json:"userId"`       // 用户id  
    PermissionId int `orm:"permission_id" json:"permissionId"` // 权限id  
}


// UserRole is the golang structure for table user_role.
type UserRole struct {
    Id     int `orm:"id,primary" json:"id"`     //         
    UserId int `orm:"user_id"    json:"userId"` // 用户id  
    RoleId int `orm:"role_id"    json:"roleId"` // 角色id  
}