# HTTP Server
[server]
	Address     = ":8199"
	ServerRoot  = "public"
	ServerAgent = "gf-app"
	LogPath     = "./runtime/log/server"

# Logger.
[logger]
    Path        = "./runtime/log/app"
    Level       = "all"
    Stdout      = true

# Template.
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["{{", "}}"]

# Database.
[database]
    link  = "mysql:root:root@tcp(127.0.0.1:3306)/go-admin"
    debug = true
    # Database logger.
    [database.logger]
        Path   = "./runtime/log/sql"
        Level  = "all"
        Stdout = true

[gfcli]
    [[gfcli.gen.dao]]
        link  = "mysql:root:root@tcp(127.0.0.1:3306)/go-admin"

[api]
    Key = "LV4ZJZK0AAyUurZ0vqud"
    ExpiredAt = 86400