// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"go-admin/app/dao/internal"
)

// userPermissionDao is the manager for logic model data accessing and custom defined data operations functions management. 
// You can define custom methods on it to extend its functionality as you wish.
type userPermissionDao struct {
	*internal.UserPermissionDao
}

var (
	// UserPermission is globally public accessible object for table user_permission operations.
	UserPermission userPermissionDao
)

func init() {
	UserPermission = userPermissionDao{
		internal.NewUserPermissionDao(),
	}
}

// Fill with you ideas below.