// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// UserPermissionDao is the manager for logic model data accessing and custom defined data operations functions management.
type UserPermissionDao struct {
	gmvc.M                                      // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C       userPermissionColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.	
	DB      gdb.DB                              // DB is the raw underlying database management object.
	Table   string                              // Table is the underlying table name of the DAO.
}

// UserPermissionColumns defines and stores column names for table user_permission.
type userPermissionColumns struct {
	Id            string //         
    UserId        string // 用户id  
    PermissionId  string // 权限id
}

// NewUserPermissionDao creates and returns a new DAO object for table data access.
func NewUserPermissionDao() *UserPermissionDao {
    columns := userPermissionColumns{
		Id:           "id",             
            UserId:       "user_id",        
            PermissionId: "permission_id",
	}
	return &UserPermissionDao{
		C: 	   columns,
		M:     g.DB("default").Model("user_permission").Safe(),
		DB:    g.DB("default"),
		Table: "user_permission",
	}
}